###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')

def coerce(cls: Type[BaseModel], parsed: Any) -> Any:
  try:
    return cls.model_validate({"inner": parsed}).inner # type: ignore
  except ValidationError as e:
    raise TypeError(
      "Internal BAML error while casting output to {}\n{}".format(
        cls.__name__,
        pprint.pformat(parsed)
      )
    ) from e

# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def CandidateEvaluation(
        self,
        CANDIDATE_RESUME: str,JD: str,github: Union[str, Optional[None]],
        baml_options: BamlCallOptions = {},
    ) -> types.Evaluation:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "CandidateEvaluation",
        {
          "CANDIDATE_RESUME": CANDIDATE_RESUME,"JD": JD,"github": github,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      mdl = create_model("CandidateEvaluationReturnType", inner=(types.Evaluation, ...))
      return coerce(mdl, raw.parsed())
    
    async def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractResume",
        {
          "resume": resume,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      mdl = create_model("ExtractResumeReturnType", inner=(types.Resume, ...))
      return coerce(mdl, raw.parsed())
    
    async def FinalEvaluationOfCandidate(
        self,
        CANDIDATE_RESUME: str,JD: str,github: Union[str, Optional[None]],CallSummaryText: str,evaluation: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FinalEvaluation:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "FinalEvaluationOfCandidate",
        {
          "CANDIDATE_RESUME": CANDIDATE_RESUME,"JD": JD,"github": github,"CallSummaryText": CallSummaryText,"evaluation": evaluation,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      mdl = create_model("FinalEvaluationOfCandidateReturnType", inner=(types.FinalEvaluation, ...))
      return coerce(mdl, raw.parsed())
    
    async def FixCallSummary(
        self,
        callsummary: str,name: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CallSummaryOutput:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "FixCallSummary",
        {
          "callsummary": callsummary,"name": name,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      mdl = create_model("FixCallSummaryReturnType", inner=(types.CallSummaryOutput, ...))
      return coerce(mdl, raw.parsed())
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def CandidateEvaluation(
        self,
        CANDIDATE_RESUME: str,JD: str,github: Union[str, Optional[None]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Evaluation, types.Evaluation]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "CandidateEvaluation",
        {
          "CANDIDATE_RESUME": CANDIDATE_RESUME,
          "JD": JD,
          "github": github,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      mdl = create_model("CandidateEvaluationReturnType", inner=(types.Evaluation, ...))
      partial_mdl = create_model("CandidateEvaluationPartialReturnType", inner=(partial_types.Evaluation, ...))

      return baml_py.BamlStream[partial_types.Evaluation, types.Evaluation](
        raw,
        lambda x: coerce(partial_mdl, x),
        lambda x: coerce(mdl, x),
        self.__ctx_manager.get(),
      )
    
    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Resume, types.Resume]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractResume",
        {
          "resume": resume,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      mdl = create_model("ExtractResumeReturnType", inner=(types.Resume, ...))
      partial_mdl = create_model("ExtractResumePartialReturnType", inner=(partial_types.Resume, ...))

      return baml_py.BamlStream[partial_types.Resume, types.Resume](
        raw,
        lambda x: coerce(partial_mdl, x),
        lambda x: coerce(mdl, x),
        self.__ctx_manager.get(),
      )
    
    def FinalEvaluationOfCandidate(
        self,
        CANDIDATE_RESUME: str,JD: str,github: Union[str, Optional[None]],CallSummaryText: str,evaluation: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.FinalEvaluation, types.FinalEvaluation]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "FinalEvaluationOfCandidate",
        {
          "CANDIDATE_RESUME": CANDIDATE_RESUME,
          "JD": JD,
          "github": github,
          "CallSummaryText": CallSummaryText,
          "evaluation": evaluation,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      mdl = create_model("FinalEvaluationOfCandidateReturnType", inner=(types.FinalEvaluation, ...))
      partial_mdl = create_model("FinalEvaluationOfCandidatePartialReturnType", inner=(partial_types.FinalEvaluation, ...))

      return baml_py.BamlStream[partial_types.FinalEvaluation, types.FinalEvaluation](
        raw,
        lambda x: coerce(partial_mdl, x),
        lambda x: coerce(mdl, x),
        self.__ctx_manager.get(),
      )
    
    def FixCallSummary(
        self,
        callsummary: str,name: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.CallSummaryOutput, types.CallSummaryOutput]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "FixCallSummary",
        {
          "callsummary": callsummary,
          "name": name,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      mdl = create_model("FixCallSummaryReturnType", inner=(types.CallSummaryOutput, ...))
      partial_mdl = create_model("FixCallSummaryPartialReturnType", inner=(partial_types.CallSummaryOutput, ...))

      return baml_py.BamlStream[partial_types.CallSummaryOutput, types.CallSummaryOutput](
        raw,
        lambda x: coerce(partial_mdl, x),
        lambda x: coerce(mdl, x),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]